version: "3.3"
services:
  web-service-hotel-api-container:
    image: web-service-hotel-api
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-docker
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - springboot-mysql-docker
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotel_db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password

networks:
  springboot-mysql-docker: