server:
  port: ${PORT:8080}

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/hotel_db?allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Kuala_Lumpur&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect